### ISSUE TITLE
Packages for gcc-7 and clang-5.0 aren't installed properly in .travis.yml.

### ISSUE THREAD

**Issue by skorezore** [juliantorreno/opengl-demo#1]
Issue surfaced after some build server downtime, presumably due to spooky caching magic :ghost:

**Comment by jtorreno** [comment]
Likely to be related to network issues within Travis CI referenced in #2.

**Comment by jtorreno** [comment]
...or not. Travis trusty does not have support for gcc-7 as per https://github.com/travis-ci/apt-package-whitelist/issues/3933
